# Generated by Django 6.0.2 on 2026-02-19 13:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.CharField(db_index=True, help_text='Auto-generated resident ID', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, help_text='Jr., Sr., III, etc.', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be 9-15 digits. Can start with +', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('purok', models.CharField(help_text='Purok/Zone number', max_length=50)),
                ('street', models.CharField(max_length=200)),
                ('is_pwd', models.BooleanField(default=False, verbose_name='Person with Disability')),
                ('is_senior', models.BooleanField(default=False, verbose_name='Senior Citizen (60+)')),
                ('is_4ps', models.BooleanField(default=False, verbose_name='4Ps Beneficiary')),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('self_employed', 'Self-Employed'), ('student', 'Student'), ('retired', 'Retired')], max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('has_portal_account', models.BooleanField(default=False, help_text='Has resident portal account created')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'residents',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='residents_last_na_fecfe2_idx'), models.Index(fields=['purok'], name='residents_purok_e9ab4a_idx')],
            },
        ),
    ]
