# Generated by Django 6.0.2 on 2026-02-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='relationship_to_head',
            field=models.CharField(blank=True, help_text='Relationship to household head (e.g., Spouse, Child, Parent)', max_length=50),
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_id', models.CharField(db_index=True, help_text='Auto-generated household ID', max_length=20, unique=True)),
                ('street', models.CharField(max_length=200)),
                ('purok', models.CharField(max_length=50)),
                ('housing_type', models.CharField(choices=[('owned', 'Owned'), ('rented', 'Rented'), ('informal', 'Informal Settler'), ('rent_free', 'Rent-Free')], max_length=20)),
                ('housing_condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('dilapidated', 'Dilapidated'), ('makeshift', 'Makeshift/Informal')], max_length=20)),
                ('has_electricity', models.BooleanField(default=True)),
                ('has_water', models.BooleanField(default=True)),
                ('water_source', models.CharField(blank=True, choices=[('piped', 'Piped Water'), ('well', 'Well'), ('public', 'Public Tap'), ('other', 'Other')], max_length=50)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, help_text='Total household monthly income', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households_created', to=settings.AUTH_USER_MODEL)),
                ('household_head', models.OneToOneField(blank=True, help_text='Designated head of household', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_household', to='residents.resident')),
            ],
            options={
                'db_table': 'households',
                'ordering': ['household_id'],
            },
        ),
        migrations.AddField(
            model_name='resident',
            name='household',
            field=models.ForeignKey(blank=True, help_text='Household this resident belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='residents.household'),
        ),
    ]
