# Generated by Django 6.0.3 on 2026-03-25 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUPERADMIN_CREATED', 'Super Admin Created'), ('ADMIN_CREATED', 'Admin Created'), ('STAFF_CREATED', 'Staff Created'), ('RESIDENT_ACCOUNT_CREATED', 'Resident Account Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_REACTIVATED', 'User Reactivated'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('TWO_FA_SETUP', '2FA Setup'), ('TWO_FA_VERIFIED', '2FA Verified'), ('TWO_FA_FAILED', '2FA Failed'), ('PASSWORD_CHANGED', 'Password Changed'), ('EMAIL_VERIFIED', 'Email Verified'), ('RESIDENT_CREATED', 'Resident Record Created'), ('RESIDENT_UPDATED', 'Resident Record Updated'), ('RESIDENT_DELETED', 'Resident Record Deleted')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
