# Generated by Django 6.0.3 on 2026-03-26 16:32

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0003_resident_personal_fields_and_optional_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(help_text='Stable internal identifier that never changes, e.g. "water_source"', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Display label used in reports, e.g. "Water Source"', max_length=200)),
                ('level', models.CharField(choices=[('household', 'Household'), ('family', 'Family'), ('person', 'Person')], help_text='Which model level this field belongs to', max_length=10)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('multiselect', 'Multi-select'), ('boolean', 'Yes/No'), ('date', 'Date')], default='select', max_length=15)),
                ('canonical_options', models.JSONField(default=list, help_text='Stable list of all possible values across all years. Example: [{"value":"level_1","label":"Nature/Spring"}, ...]')),
                ('year_map', models.JSONField(default=dict, help_text='Maps year → {field_name, value_map} — see class docstring')),
                ('notes', models.TextField(blank=True, help_text='Document why mappings changed between years')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Field Mapping',
                'verbose_name_plural': 'Field Mappings',
                'ordering': ['level', 'canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(db_index=True, help_text='Survey year, e.g. 2024')),
                ('version', models.PositiveSmallIntegerField(default=1, help_text='Increments if form is revised within the same year (2024 v1, 2024 v2)')),
                ('name', models.CharField(help_text='Human-readable label, e.g. "Barangay Household Survey 2024 v1"', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(help_text='Full form definition — see class docstring for structure')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only one schema per year should be active for new data entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Schema',
                'verbose_name_plural': 'Form Schemas',
                'ordering': ['-year', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('household_number', models.CharField(help_text='Barangay-assigned code, e.g. "PRK3-2024-001". Never changes.', max_length=30, unique=True)),
                ('address', models.TextField(blank=True, help_text='Full street address within the purok')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude for map display', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude for map display', max_digits=9, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Occupied'), ('VACANT', 'Vacant'), ('ABANDONED', 'Abandoned'), ('DEMOLISHED', 'Demolished')], db_index=True, default='ACTIVE', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL)),
                ('purok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='households', to='residents.purok')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Household',
                'verbose_name_plural': 'Households',
                'ordering': ['purok', 'household_number'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('SURVEY', 'Household Survey'), ('FAMILY', 'Family'), ('PERSON', 'Person'), ('PROGRAM', 'Program Availed')], db_index=True, max_length=8)),
                ('target_id', models.UUIDField(db_index=True, help_text='UUID of the specific record that was changed')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Soft Deleted'), ('RESTORED', 'Restored'), ('VERIFIED', 'Verified'), ('REVISION', 'Sent for Revision')], max_length=10)),
                ('changed_fields', models.JSONField(default=dict, help_text='{"field_name": {"old": "...", "new": "..."}}')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('survey_year', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Denormalized for filtering change history by year', null=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiling_changes', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='profiling.household')),
            ],
            options={
                'verbose_name': 'Household Change Log',
                'verbose_name_plural': 'Household Change Logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdSurvey',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_year', models.PositiveSmallIntegerField(db_index=True, help_text='Denormalized year for fast filtering without JOIN to FormSchema')),
                ('surveyed_at', models.DateField(blank=True, help_text='Date the survey was physically conducted', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REVISION', 'Needs Revision')], db_index=True, default='DRAFT', max_length=10)),
                ('data', models.JSONField(default=dict, help_text='Answers to household-level form fields. Keys match FormSchema field IDs.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Supervisor notes during verification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL)),
                ('form_schema', models.ForeignKey(help_text='Which form version was used — determines what is in data JSON', on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='profiling.formschema')),
                ('household', models.ForeignKey(help_text='The physical household this survey is about', on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='profiling.household')),
                ('surveyed_by', models.ForeignKey(blank=True, help_text='Staff member who collected this data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_surveys', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Household Survey',
                'verbose_name_plural': 'Household Surveys',
                'ordering': ['-survey_year', 'household'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_number', models.PositiveSmallIntegerField(help_text='Sequential within this survey (1, 2, 3...). Never changes.')),
                ('monthly_income_bracket', models.CharField(choices=[('NO_INCOME', 'No Income'), ('BELOW_5K', 'Below ₱5,000'), ('5K_10K', '₱5,000 – ₱9,999'), ('10K_20K', '₱10,000 – ₱19,999'), ('20K_30K', '₱20,000 – ₱29,999'), ('30K_50K', '₱30,000 – ₱49,999'), ('ABOVE_50K', '₱50,000 and above'), ('UNSPECIFIED', 'Not Specified')], db_index=True, default='UNSPECIFIED', max_length=12)),
                ('data', models.JSONField(default=dict, help_text='Answers to family-level form fields')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('household_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='profiling.householdsurvey')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ['household_survey', 'family_number'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('survey_year', models.PositiveSmallIntegerField(db_index=True)),
                ('level', models.CharField(choices=[('household', 'Household'), ('family', 'Family'), ('person', 'Person')], max_length=10)),
                ('source_id', models.UUIDField(blank=True, db_index=True, help_text='UUID of the Family or Person this value came from. NULL for household-level fields.', null=True)),
                ('canonical_name', models.CharField(db_index=True, help_text='FieldMapping.canonical_name', max_length=100)),
                ('raw_value', models.CharField(help_text='Original value from the data JSON, exactly as stored', max_length=500)),
                ('canonical_value', models.CharField(help_text='Value translated to the canonical vocabulary via FieldMapping', max_length=500)),
                ('household_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_data', to='profiling.householdsurvey')),
            ],
            options={
                'verbose_name': 'Normalized Data',
                'verbose_name_plural': 'Normalized Data',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('HEAD', 'Head of Family'), ('SPOUSE', 'Spouse / Partner'), ('CHILD', 'Child'), ('PARENT', 'Parent of Head'), ('SIBLING', 'Sibling'), ('RELATIVE', 'Other Relative'), ('NON_RELATIVE', 'Non-Relative')], db_index=True, default='NON_RELATIVE', max_length=15)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('suffix', models.CharField(blank=True, help_text='Jr., Sr., III, etc.', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, db_index=True, null=True)),
                ('age_at_survey', models.PositiveSmallIntegerField(blank=True, help_text='Age recorded at time of survey — preserved even as DOB ages', null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other / Prefer not to say')], db_index=True, max_length=10)),
                ('civil_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated'), ('ANNULLED', 'Annulled'), ('LIVE_IN', 'Live-in')], db_index=True, max_length=10)),
                ('educational_attainment', models.CharField(blank=True, choices=[('NO_FORMAL', 'No Formal Education'), ('KINDER', 'Kinder'), ('ELEM', 'Elementary (Ongoing)'), ('ELEM_GRAD', 'Elementary Graduate'), ('JHS', 'Junior High School (Ongoing)'), ('JHS_GRAD', 'Junior High School Graduate'), ('SHS', 'Senior High School (Ongoing)'), ('SHS_GRAD', 'Senior High School Graduate'), ('VOCATIONAL', 'Vocational / TESDA'), ('COLLEGE', 'College (Ongoing)'), ('COLLEGE_GRAD', 'College Graduate'), ('POST_GRAD', 'Post-Graduate')], db_index=True, max_length=15)),
                ('is_registered_voter', models.BooleanField(blank=True, null=True)),
                ('sectors', models.JSONField(default=list, help_text='List of sector codes. Example: ["PWD", "SOLO_PARENT"]. Query: Person.objects.filter(sectors__contains=["PWD"])')),
                ('data', models.JSONField(default=dict, help_text='Answers to person-level form fields')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='profiling.family')),
                ('resident', models.ForeignKey(blank=True, help_text='Links to portal Resident record if one exists', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiling_entries', to='residents.resident')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['family', 'role', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramAvailed',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program_type', models.CharField(choices=[('FINANCIAL', 'Financial Assistance'), ('EDUCATIONAL', 'Educational Assistance / Scholarship'), ('MEDICAL', 'Medical Assistance'), ('LIVELIHOOD', 'Livelihood / Skills Training'), ('4PS', '4Ps / Pantawid Pamilya'), ('NATIONAL', 'National Government (DSWD / DOLE / DAR)'), ('RELIEF', 'Relief Goods / Emergency Aid'), ('HOUSING', 'Housing Assistance'), ('OTHER', 'Other')], db_index=True, max_length=12)),
                ('program_name', models.CharField(blank=True, help_text='Specific program name, e.g. "AICS", "TUPAD", "DSWD SLP"', max_length=200)),
                ('date_availed', models.DateField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference_no', models.CharField(blank=True, help_text='Government control or reference number', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict, help_text='Any extra structured fields for this program')),
                ('beneficiary', models.ForeignKey(blank=True, help_text='Named beneficiary, if program is for one person rather than whole family', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_availed', to='profiling.person')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs_availed', to='profiling.family')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Program Availed',
                'verbose_name_plural': 'Programs Availed',
                'ordering': ['-date_availed', 'program_type'],
            },
        ),
        migrations.AddIndex(
            model_name='formschema',
            index=models.Index(fields=['year', 'is_active'], name='profiling_f_year_79be83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formschema',
            unique_together={('year', 'version')},
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['purok', 'status'], name='profiling_h_purok_i_da0b00_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['is_deleted', 'status'], name='profiling_h_is_dele_a80fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='householdchangelog',
            index=models.Index(fields=['household', 'changed_at'], name='profiling_h_househo_b0c094_idx'),
        ),
        migrations.AddIndex(
            model_name='householdchangelog',
            index=models.Index(fields=['target_type', 'target_id'], name='profiling_h_target__821770_idx'),
        ),
        migrations.AddIndex(
            model_name='householdchangelog',
            index=models.Index(fields=['changed_by', 'changed_at'], name='profiling_h_changed_3ff10d_idx'),
        ),
        migrations.AddIndex(
            model_name='householdsurvey',
            index=models.Index(fields=['survey_year', 'status'], name='profiling_h_survey__874a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='householdsurvey',
            index=models.Index(fields=['household', 'survey_year'], name='profiling_h_househo_0033ae_idx'),
        ),
        migrations.AddIndex(
            model_name='householdsurvey',
            index=models.Index(fields=['is_deleted', 'survey_year'], name='profiling_h_is_dele_97dc5a_idx'),
        ),
        migrations.AddIndex(
            model_name='householdsurvey',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='household_survey_data_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='householdsurvey',
            unique_together={('household', 'survey_year')},
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['household_survey', 'is_deleted'], name='profiling_f_househo_b00c21_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['monthly_income_bracket', 'is_deleted'], name='profiling_f_monthly_d00e20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('household_survey', 'family_number')},
        ),
        migrations.AddIndex(
            model_name='normalizeddata',
            index=models.Index(fields=['canonical_name', 'canonical_value', 'survey_year'], name='norm_canonical_year_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizeddata',
            index=models.Index(fields=['household_survey', 'canonical_name'], name='norm_survey_canonical_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizeddata',
            index=models.Index(fields=['survey_year', 'level'], name='norm_year_level_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='profiling_p_last_na_67dc85_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['family', 'role'], name='profiling_p_family__2e2c08_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['gender', 'is_deleted'], name='profiling_p_gender_445dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['educational_attainment', 'is_deleted'], name='profiling_p_educati_8869d0_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['date_of_birth'], name='profiling_p_date_of_936a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sectors'], name='person_sectors_gin'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='person_data_gin'),
        ),
        migrations.AddIndex(
            model_name='programavailed',
            index=models.Index(fields=['program_type', 'date_availed'], name='profiling_p_program_c6c797_idx'),
        ),
        migrations.AddIndex(
            model_name='programavailed',
            index=models.Index(fields=['family', 'program_type'], name='profiling_p_family__c2995f_idx'),
        ),
        migrations.AddIndex(
            model_name='programavailed',
            index=models.Index(fields=['is_deleted', 'program_type'], name='profiling_p_is_dele_55bab4_idx'),
        ),
    ]
