# Generated by Django 6.0.3 on 2026-03-25 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DECEASED', 'Deceased'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
                'ordering': ['-created_at'],
            },
        ),
    ]
