# Generated by Django 6.0.3 on 2026-03-25 14:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_admin_fields'),
        ('residents', '0002_staff_models_and_purok'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('department', models.CharField(blank=True, choices=[('HEALTH', 'Health Services'), ('SOCIAL', 'Social Services'), ('RECORDS', 'Records Management'), ('SECURITY', 'Security & Peace Order'), ('ENVIRONMENT', 'Environment & Sanitation'), ('LIVELIHOOD', 'Livelihood & Employment'), ('GENERAL', 'General Services')], max_length=15)),
                ('work_start', models.TimeField(default=datetime.time(8, 0))),
                ('work_end', models.TimeField(default=datetime.time(17, 0))),
                ('allow_weekend', models.BooleanField(default=False)),
                ('allow_after_hours', models.BooleanField(default=False)),
                ('perm_generate_reports', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
            },
        ),
        migrations.CreateModel(
            name='StaffPurokPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('purok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_permissions', to='residents.purok')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purok_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Purok Permission',
                'verbose_name_plural': 'Staff Purok Permissions',
                'unique_together': {('user', 'purok')},
            },
        ),
    ]
